### ISSUE TITLE
tima-r Error on ESI(-) 

### ISSUE THREAD

**Issue by anani-a-missinou** [taxonomicallyinformedannotation/tima-r#116]
Hi dear developers,

I ran my plant metabolomic data on the Sirius version (v5.8.5) and I would like to provide it to your tima-r GUI. 

Now everything is executed correctly for ESI(+) files, however, I have another error with the ESI(-) files, for which TIMA stops immediately after the start. I always get this error:

(base) $ pwd
/mnt/d/tools/computational_metabolomics/tima-r

## MGF file
**(base) $ more data/source/brassimet_leaves-roots_pacs_neg.mgf**
BEGIN IONS
FEATURE_ID=315
PEPMASS=260.911
SCANS=315
RTINSECONDS=36.518
CHARGE=0-
MSLEVEL=2
MERGED_STATS=1 / 4 (0 removed due to low quality, 3 removed due to low cosine).
96.971 2.3E2
97.029 2.1E2
116.006 9.0E1
144.015 1.3E2
152.915 1.3E2
196.903 4.3E2
197.912 2.0E2
215.923 2.0E2
242.901 1.9E2
END IONS

BEGIN IONS
FEATURE_ID=3246
PEPMASS=261.127
SCANS=3246
RTINSECONDS=420.041
CHARGE=0-
MSLEVEL=2
MERGED_STATS=2 / 2 (0 removed due to low quality, 0 removed due to low cosine).
114.056 6.1E3
114.673 9.2E1
115.059 3.4E2
172.008 8.0E1
219.737 8.0E1
221.841 1.1E2
222.839 9.2E1
223.840 1.2E2
END IONS

BEGIN IONS
FEATURE_ID=391
PEPMASS=262.057
SCANS=391
RTINSECONDS=40.4
CHARGE=0-
MSLEVEL=2
MERGED_STATS=1 / 5 (1 removed due to low quality, 3 removed due to low cosine).
96.008 1.3E2
96.041 2.0E2
96.958 2.7E2
97.029 2.2E2
97.146 8.0E1
111.043 1.3E2
115.005 8.8E1
129.019 1.1E2
133.015 2.6E2
198.901 9.2E1
198.924 1.0E2
244.911 9.2E1
260.011 8.2E1
END IONS

## quant CSV
**(base) $ more data/source/brassimet_leaves-roots_pacs_neg.csv**
row ID,row m/z,row retention time,Leaves_s105_neg.mzXML Peak area,Leaves_s107_neg.mzXML Peak area,Leaves_s106_neg.mzXML Peak area,Leaves_s108_neg.mzXML Peak area,Leaves_s104_neg.mzXML Peak area,Leaves_s100_neg.m
zXML Peak area,Leaves_s110_neg.mzXML Peak area,Leaves_s103_neg.mzXML Peak area,Leaves_s102_neg.mzXML Peak area,Leaves_s10_neg.mzXML Peak area,Leaves_s101_neg.mzXML Peak area,Leaves_s109_neg.mzXML Peak area,Leave
s_s11_neg.mzXML Peak area,Leaves_s12_neg.mzXML Peak area,Leaves_s112_neg.mzXML Peak area,Leaves_s111_neg.mzXML Peak area,Leaves_s16_neg.mzXML Peak area,Leaves_s113_neg.mzXML Peak area,Leaves_s13_neg.mzXML Peak a
rea,Leaves_s115_neg.mzXML Peak area,Leaves_s15_neg.mzXML Peak area,Leaves_s14_neg.mzXML Peak area,Leaves_s114_neg.mzXML Peak area,Leaves_s116_neg.mzXML Peak area,Leaves_s3_neg.mzXML Peak area,Leaves_s19_neg.mzXM
L Peak area,Leaves_s1_neg.mzXML Peak area,Leaves_s22_neg.mzXML Peak area,Leaves_s21_neg.mzXML Peak area,Leaves_s4_neg.mzXML Peak area,Leaves_s48_neg.mzXML Peak area,Leaves_s17_neg.mzXML Peak area,Leaves_s20_neg.
mzXML Peak area,Leaves_s18_neg.mzXML Peak area,Leaves_s49_neg.mzXML Peak area,Leaves_s2_neg.mzXML Peak area,Leaves_s53_neg.mzXML Peak area,Leaves_s58_neg.mzXML Peak area,Leaves_s54_neg.mzXML Peak area,Leaves_s57
_neg.mzXML Peak area,Leaves_s55_neg.mzXML Peak area,Leaves_s50_neg.mzXML Peak area,Leaves_s61_neg.mzXML Peak area,Leaves_s59_neg.mzXML Peak area,Leaves_s60_neg.mzXML Peak area,Leaves_s51_neg.mzXML Peak area,Leav
es_s56_neg.mzXML Peak area,Leaves_s67_neg.mzXML Peak area,Leaves_s6_neg.mzXML Peak area,Leaves_s69_neg.mzXML Peak area,Leaves_s63_neg.mzXML Peak area,Leaves_s65_neg.mzXML Peak area,Leaves_s64_neg.mzXML Peak area
,Leaves_s95_neg.mzXML Peak area,Leaves_s66_neg.mzXML Peak area,Leaves_s5_neg.mzXML Peak area,Leaves_s52_neg.mzXML Peak area,Leaves_s68_neg.mzXML Peak area,Roots_s151_neg.mzXML Peak area,Roots_s143_neg.mzXML Peak
 area,Roots_s148_neg.mzXML Peak area,Roots_s153_neg.mzXML Peak area,Roots_s144_neg.mzXML Peak area,Leaves_s8_neg.mzXML Peak area,Leaves_s99_neg.mzXML Peak area,Leaves_s97_neg.mzXML Peak area,Leaves_s62_neg.mzXML
 Peak area,Leaves_s7_neg.mzXML Peak area,Roots_s152_neg.mzXML Peak area,Roots_s155_neg.mzXML Peak area,Roots_s149_neg.mzXML Peak area,Roots_s154_neg.mzXML Peak area,Leaves_s98_neg.mzXML Peak area,Leaves_s9_neg.m
zXML Peak area,Roots_s158_neg.mzXML Peak area,Leaves_s96_neg.mzXML Peak area,Roots_s145_neg.mzXML Peak area,Roots_s150_neg.mzXML Peak area,Roots_s146_neg.mzXML Peak area,Roots_s147_neg.mzXML Peak area,Roots_s159
_neg.mzXML Peak area,Roots_s163_neg.mzXML Peak area,Roots_s191_neg.mzXML Peak area,Roots_s164_neg.mzXML Peak area,Roots_s190_neg.mzXML Peak area,Roots_s157_neg.mzXML Peak area,Roots_s160_neg.mzXML Peak area,Root
s_s200_neg.mzXML Peak area,Roots_s156_neg.mzXML Peak area,Roots_s195_neg.mzXML Peak area,Roots_s192_neg.mzXML Peak area,Roots_s199_neg.mzXML Peak area,Roots_s239_neg.mzXML Peak area,Roots_s193_neg.mzXML Peak are
a,Roots_s201_neg.mzXML Peak area,Roots_s198_neg.mzXML Peak area,Roots_s205_neg.mzXML Peak area,Roots_s206_neg.mzXML Peak area,Roots_s203_neg.mzXML Peak area,Roots_s197_neg.mzXML Peak area,Roots_s194_neg.mzXML Pe
ak area,Roots_s204_neg.mzXML Peak area,Roots_s202_neg.mzXML Peak area,Roots_s246_neg.mzXML Peak area,Roots_s240_neg.mzXML Peak area,Roots_s208_neg.mzXML Peak area,Roots_s241_neg.mzXML Peak area,Roots_s235_neg.mz
XML Peak area,Roots_s234_neg.mzXML Peak area,Roots_s237_neg.mzXML Peak area,Roots_s238_neg.mzXML Peak area,Roots_s207_neg.mzXML Peak area,Roots_s209_neg.mzXML Peak area,Roots_s196_neg.mzXML Peak area,Roots_s249_
neg.mzXML Peak area,Roots_s248_neg.mzXML Peak area,Roots_s255_neg.mzXML Peak area,Roots_s242_neg.mzXML Peak area,Roots_s254_neg.mzXML Peak area,Roots_s244_neg.mzXML Peak area,Roots_s236_neg.mzXML Peak area,Roots
_s243_neg.mzXML Peak area,Roots_s253_neg.mzXML Peak area,Roots_s247_neg.mzXML Peak area,Roots_s250_neg.mzXML Peak area,Roots_s252_neg.mzXML Peak area,Roots_s251_neg.mzXML Peak area,Roots_s245_neg.mzXML Peak area

100,130.966,0.56,0.118359524,0.114366141,0.097470909,0.171647188,0.078314134,0.132567374,0.10262917,0.073907042,0.087363398,0.167423555,0.083586785,0.083056528,0.185519938,0.214336929,0.046685281,0.084452367,0.3
94850526,0.12554497,0.231144276,0.117826219,0.350494414,0.551666469,0.123136102,0.113100113,0.34841032,0.181745582,0.173918512,0.184603089,0.396488522,0.411597512,0.619168492,0.257458404,0.516767736,0.382059127,
0.162424627,0.464435715,0.289202142,0.320392414,0.390835584,0.287682347,0.082806537,0.267619676,0.074731797,0.084795028,0.216211459,0.092459928,0.13961239,0.232263818,0.398342811,0.252950667,0.485446389,0.722351
087,0.266449947,0.365256152,0.40372504,0.396192997,0.422915134,0.107207266,0.215216218,0.23036678,0.125980318,0.176236367,0.361149996,0.177535524,0.145882213,0.178686106,0.349186112,0.605522378,0.504168884,0.305
186506,0.477997589,0.24996409,0.324742384,0.329064413,0.210114434,0.223924622,0.198406945,0.374755012,0.159755149,0.204459611,0.178029252,0.268288206,0.122992569,0.384467763,0.325327204,0.265890921,0.255530334,0
.191414489,0.161217194,0.234501494,0.263236557,0.402839652,0.224514364,0.150020335,0.156708064,0.600846542,0.272381521,0.194019725,0.196014865,0.290862964,0.257400562,0.140923076,0.181654191,0.148602314,0.166559
171,0.637158131,0.231623925,0.028665003,0.27907021,0.110401305,0.209886593,0.005512331,0.295077615,0.725219787,0.407407764,0.080669843,0.15727575,0.155843448,0.15703454,0.052601668,0.083711469,0.185193059,0.1911
66218,0.134400105,0.078900341,0.092059837,0.199765076,0.302984377
1000,563.162,2.65,0.002351144,0.03138411,0.046430581,0.014016809,0.005260449,0.004008616,0.072508986,0.396423982,0.013356437,0.004448565,0.012051765,0.098101212,0.008431866,0.005981214,0.021410654,0.050678734,0.
038089105,0.084349268,0.050858932,0.051987162,0.069102974,0.04866481,0.04250397,0.14699325,0.003765456,0.028616912,0.210683055,0.019897061,0.036462679,0.005408697,0.279693167,0.043215898,0.017614623,0.069125804,
0.084617609,0.384564838,0.002452304,0.009573809,0.020431643,0.011584467,0.007009059,0.06615142,0.05622776,0.006740108,0.067586147,0.029333817,0.42955687,0.005815952,0.007845623,0.025088661,0.069593591,0.00511437
,0.06592977,0.33856677,0.1374758,0.129877649,0.150411432,0.087185535,0.001201651,0.001158871,0.000860429,0.000553256,0.00574264,0.002858157,0.051181467,0.013951043,0.138452325,0.001853842,0.000658846,0.000609875
,5.17E-05,0.000592369,0.004384863,0.047808066,0.00059398,0.017729199,0.000270717,0.001139549,0.001446078,0.001506153,0.000400213,0.000832913,0.003189604,0.000622085,0.00290863,0.000807047,0.000557532,0.000314197
,0.000478341,0.00047006,0.001805122,0.002376823,0.000186284,0.001039596,0.000769154,0.00214297,0.000438094,0.000766518,0.001013488,0.004252496,0.002525424,0.00047634,0.000599107,0.000453766,0.000503276,0.0004400
15,0.001227448,0.005811657,0.00929775,0.001421717,0.003601587,0.001167599,0.000647621,0.005993457,0.000919489,0.0007568,0.000828872,0.001315488,0.000168675,0.0003824,0.000372499,0.000759268,0.00030694,0.00021478
1,0.000407806,0.00124241,0.000529125,0.000451123
1001,437.041,2.72,0.000624998,0.023252448,0.040478891,0.102240027,0.030125466,0.024752415,0.054759215,0.037617806,0.000380606,0.004574524,0.008371286,0.024890506,0.009921127,0.109720779,0.007969596,0.020351836,0
.147917065,0.028021216,0.060752109,0.026415109,0.106651716,0.255464735,0.024410854,0.058767716,0.059151505,0.017005866,0.000435865,0.032608933,0.176142118,0.024197179,0.00265735,0.118636202,0.239477228,0.1205456
99,0.001349849,0.003628028,0.03424252,0.001808273,0.013031311,0.03145576,0.000187685,0.041690739,0.062251897,0.014385268,0.04331612,0.001983793,0.04187734,0.032453168,0.036040942,0.089107692,0.170076844,0.376465
754,0.13182893,0.001633818,0.038041613,0.000667109,0.001127784,0.055635501,0.013034202,0.006146114,0.040597573,0.005443156,0.040225873,0.000662105,0.001413735,0.039910218,0.089671036,0.031056851,0.049328382,0.03
3931334,0.04224432,0.009172607,0.035145301,0.14643393,0.01677115,0.003833406,0.037492139,0.01319142,0.124096625,0.005026297,0.005293217,0.004968032,0.00505352,0.045062694,0.024076275,0.020817226,0.027894917,0.01
7030938,0.01438004,0.052608469,0.038815987,0.032438247,0.049926609,0.0108978,0.00871716,0.099908006,0.021272003,0.019307038,0.00671117,0.025057854,0.010605139,0.003157577,0.005069026,0.006158831,0.017080881,0.01
802134,0.020128752,0.002023062,0.015277286,0.004642086,0.019646127,0.000519576,0.11100252,0.13890675,0.005819892,0.008077479,0.024194966,0.013763824,0.003499291,0.001447746,0.011738861,0.025926878,0.023668904,0.
007519223,0.005826053,0.008396906,0.011391617,0.018492346
1002,195.033,2.66,0.001220376,0.000470635,0.000881454,0.000824582,0.00592435,0.002716073,0.009460687,0.001228953,0.003874223,0.001217398,0.003967937,0.000991979,0.003855854,0.001264516,0.00094477,0.00074868,0.00
5561745,0.000901568,0.009529964,0.000533221,0.002314578,0.00219105,0.002938703,0.003468522,0.000588096,0.000208168,0.00429401,0.000957859,0.000519271,0.011642066,0.004895464,0.001002621,0.025701217,0.002813693,0
.000827531,0.002910007,0.005722647,0.000843999,0.002526907,0.000375564,0.003619382,0.013521241,0.000462398,0.000514326,0.001226914,0.008776345,0.000994929,0.008010728,0.007805144,0.010312023,0.015755081,0.006082
561,0.001565106,0.003598776,0.008402092,0.009736605,0.011030936,0.000867071,0.000726906,0.002165146,0.000984807,0.001992743,0.002718797,0.006918341,0.004269652,0.003602457,0.003300829,0.002345905,0.001448693,0.0
08619008,0.002063716,0.00486385,0.02586053,0.003093191,0.027254628,0.000723341,0.007920961,0.004848376,0.005207263,0.013313209,0.004457211,0.002356766,0.008652608,0.001669799,0.003144352,0.004942968,0.013862035

## taxonomic metadata
**(base) $ more data/source/brassimet_leaves-roots-neg_pacs_taxonomic_metadata_v2.tsv**
filename        ATTRIBUTE_species
Leaves_s115_neg.mzXML   Brassica oleracea
Leaves_s21_neg.mzXML    Brassica oleracea
Leaves_s68_neg.mzXML    Brassica oleracea
Leaves_s105_neg.mzXML   Brassica oleracea
Leaves_s11_neg.mzXML    Brassica oleracea
Leaves_s58_neg.mzXML    Brassica oleracea
Leaves_s106_neg.mzXML   Brassica oleracea
Leaves_s12_neg.mzXML    Brassica oleracea
Leaves_s59_neg.mzXML    Brassica oleracea
Leaves_s107_neg.mzXML   Brassica oleracea
Leaves_s13_neg.mzXML    Brassica oleracea
Leaves_s60_neg.mzXML    Brassica oleracea
Leaves_s108_neg.mzXML   Brassica oleracea
Leaves_s14_neg.mzXML    Brassica oleracea
Leaves_s61_neg.mzXML    Brassica oleracea
Leaves_s109_neg.mzXML   Brassica oleracea
Leaves_s15_neg.mzXML    Brassica oleracea
Leaves_s62_neg.mzXML    Brassica oleracea
Leaves_s110_neg.mzXML   Brassica oleracea
Leaves_s16_neg.mzXML    Brassica oleracea
Leaves_s63_neg.mzXML    Brassica oleracea
Leaves_s111_neg.mzXML   Brassica oleracea
Leaves_s17_neg.mzXML    Brassica oleracea
Leaves_s64_neg.mzXML    Brassica oleracea
Leaves_s112_neg.mzXML   Brassica oleracea
Leaves_s18_neg.mzXML    Brassica oleracea
Leaves_s65_neg.mzXML    Brassica oleracea
Leaves_s113_neg.mzXML   Brassica oleracea
Leaves_s19_neg.mzXML    Brassica oleracea
Leaves_s66_neg.mzXML    Brassica oleracea
Leaves_s114_neg.mzXML   Brassica oleracea
Leaves_s20_neg.mzXML    Brassica oleracea
Leaves_s67_neg.mzXML    Brassica oleracea
Leaves_s116_neg.mzXML   Brassica rapa
Leaves_s22_neg.mzXML    Brassica rapa
Leaves_s69_neg.mzXML    Brassica rapa
Leaves_s1_neg.mzXML     Brassica rapa
Leaves_s48_neg.mzXML    Brassica rapa
Leaves_s95_neg.mzXML    Brassica rapa
Leaves_s2_neg.mzXML     Brassica rapa
Leaves_s49_neg.mzXML    Brassica rapa
Leaves_s96_neg.mzXML    Brassica rapa
Leaves_s3_neg.mzXML     Brassica rapa
Leaves_s50_neg.mzXML    Brassica rapa
Leaves_s97_neg.mzXML    Brassica rapa
Leaves_s4_neg.mzXML     Brassica rapa
Leaves_s51_neg.mzXML    Brassica rapa
Leaves_s98_neg.mzXML    Brassica rapa
Leaves_s5_neg.mzXML     Brassica rapa
Leaves_s52_neg.mzXML    Brassica rapa
Leaves_s99_neg.mzXML    Brassica rapa
Leaves_s100_neg.mzXML   Brassica rapa
Leaves_s53_neg.mzXML    Brassica rapa
Leaves_s6_neg.mzXML     Brassica rapa
Leaves_s101_neg.mzXML   Brassica rapa
Leaves_s54_neg.mzXML    Brassica rapa
Leaves_s7_neg.mzXML     Brassica rapa
Leaves_s102_neg.mzXML   Brassica rapa
Leaves_s55_neg.mzXML    Brassica rapa
Leaves_s8_neg.mzXML     Brassica rapa
Leaves_s103_neg.mzXML   Brassica rapa
Leaves_s56_neg.mzXML    Brassica rapa
Leaves_s9_neg.mzXML     Brassica rapa
Leaves_s10_neg.mzXML    Brassica rapa
Leaves_s104_neg.mzXML   Brassica rapa
Leaves_s57_neg.mzXML    Brassica rapa
Roots_s163_neg.mzXML    Brassica oleracea
Roots_s208_neg.mzXML    Brassica oleracea
Roots_s254_neg.mzXML    Brassica oleracea
Roots_s153_neg.mzXML    Brassica oleracea
Roots_s200_neg.mzXML    Brassica oleracea
Roots_s244_neg.mzXML    Brassica oleracea
Roots_s154_neg.mzXML    Brassica oleracea
Roots_s201_neg.mzXML    Brassica oleracea
Roots_s245_neg.mzXML    Brassica oleracea
Roots_s155_neg.mzXML    Brassica oleracea
Roots_s246_neg.mzXML    Brassica oleracea
Roots_s156_neg.mzXML    Brassica oleracea
Roots_s202_neg.mzXML    Brassica oleracea
Roots_s247_neg.mzXML    Brassica oleracea
Roots_s157_neg.mzXML    Brassica oleracea
Roots_s203_neg.mzXML    Brassica oleracea
Roots_s248_neg.mzXML    Brassica oleracea
Roots_s158_neg.mzXML    Brassica oleracea
Roots_s204_neg.mzXML    Brassica oleracea
Roots_s249_neg.mzXML    Brassica oleracea
Roots_s159_neg.mzXML    Brassica oleracea
Roots_s205_neg.mzXML    Brassica oleracea
Roots_s250_neg.mzXML    Brassica oleracea
Roots_s160_neg.mzXML    Brassica oleracea
Roots_s206_neg.mzXML    Brassica oleracea
Roots_s251_neg.mzXML    Brassica oleracea
Roots_s207_neg.mzXML    Brassica oleracea
Roots_s252_neg.mzXML    Brassica oleracea
Roots_s253_neg.mzXML    Brassica oleracea
Roots_s164_neg.mzXML    Brassica rapa
Roots_s209_neg.mzXML    Brassica rapa
Roots_s255_neg.mzXML    Brassica rapa
Roots_s143_neg.mzXML    Brassica rapa
Roots_s190_neg.mzXML    Brassica rapa
Roots_s234_neg.mzXML    Brassica rapa
Roots_s144_neg.mzXML    Brassica rapa
Roots_s191_neg.mzXML    Brassica rapa
Roots_s235_neg.mzXML    Brassica rapa
Roots_s145_neg.mzXML    Brassica rapa
Roots_s192_neg.mzXML    Brassica rapa
Roots_s236_neg.mzXML    Brassica rapa
Roots_s146_neg.mzXML    Brassica rapa
Roots_s193_neg.mzXML    Brassica rapa
Roots_s237_neg.mzXML    Brassica rapa
Roots_s147_neg.mzXML    Brassica rapa
Roots_s194_neg.mzXML    Brassica rapa
Roots_s238_neg.mzXML    Brassica rapa
Roots_s148_neg.mzXML    Brassica rapa
Roots_s195_neg.mzXML    Brassica rapa
Roots_s239_neg.mzXML    Brassica rapa
Roots_s149_neg.mzXML    Brassica rapa
Roots_s196_neg.mzXML    Brassica rapa
Roots_s240_neg.mzXML    Brassica rapa
Roots_s150_neg.mzXML    Brassica rapa
Roots_s197_neg.mzXML    Brassica rapa
Roots_s241_neg.mzXML    Brassica rapa
Roots_s151_neg.mzXML    Brassica rapa
Roots_s198_neg.mzXML    Brassica rapa
Roots_s242_neg.mzXML    Brassica rapa
Roots_s152_neg.mzXML    Brassica rapa
Roots_s199_neg.mzXML    Brassica rapa
Roots_s243_neg.mzXML    Brassica rapa

## Error after running of tima-r
tima-gui-1 | 2024-01-17 06:36:00.102067 Changing filenames
tima-gui-1 | 2024-01-17 06:36:00.102297 Exporting params ...
tima-gui-1 | ● completed target par_usr_pre_lib_sop_hmd [0.199 seconds]
tima-gui-1 | ▶ dispatched target par_usr_pre_lib_sop_clo
tima-gui-1 | 2024-01-17 06:36:00.317971 Loading default params
tima-gui-1 | 2024-01-17 06:36:00.514703 All params
tima-gui-1 | 2024-01-17 06:36:00.515034 Small params
tima-gui-1 | 2024-01-17 06:36:00.515138 Changing params
tima-gui-1 | 2024-01-17 06:36:00.515222 Changing filenames
tima-gui-1 | 2024-01-17 06:36:00.51538 Exporting params ...
tima-gui-1 | ● completed target par_usr_pre_lib_sop_clo [0.205 seconds]
tima-gui-1 | ▶ dispatched target par_usr_cre_edg_spe
tima-gui-1 | 2024-01-17 06:36:00.75158 Loading default params
tima-gui-1 | 2024-01-17 06:36:00.931716 All params
tima-gui-1 | 2024-01-17 06:36:00.932072 Small params
tima-gui-1 | 2024-01-17 06:36:00.932204 Changing params
tima-gui-1 | 2024-01-17 06:36:00.93233 Changing filenames
tima-gui-1 | 2024-01-17 06:36:01.004152 Exporting params ...
tima-gui-1 | ● completed target par_usr_cre_edg_spe [0.283 seconds]
tima-gui-1 | ▶ dispatched target par_usr_pre_lib_sop_lot
tima-gui-1 | 2024-01-17 06:36:01.21768 Loading default params
tima-gui-1 | 2024-01-17 06:36:01.41915 All params
tima-gui-1 | 2024-01-17 06:36:01.419487 Small params
tima-gui-1 | 2024-01-17 06:36:01.419584 Changing params
tima-gui-1 | 2024-01-17 06:36:01.41967 Changing filenames
tima-gui-1 | 2024-01-17 06:36:01.419845 Exporting params ...
tima-gui-1 | ● completed target par_usr_pre_lib_sop_lot [0.209 seconds]
tima-gui-1 | ▶ dispatched target par_wei_ann
tima-gui-1 | ● completed target par_wei_ann [0.018 seconds]
tima-gui-1 | ▶ dispatched target par_ann_spe
tima-gui-1 | ● completed target par_ann_spe [0.038 seconds]
tima-gui-1 | ▶ dispatched target par_ann_mas
tima-gui-1 | ● completed target par_ann_mas [0.02 seconds]
tima-gui-1 | ▶ dispatched target par_cre_edg_spe
tima-gui-1 | ● completed target par_cre_edg_spe [0.016 seconds]
tima-gui-1 | ▶ dispatched target input_spectra
tima-gui-1 | ● completed target input_spectra [0 seconds]
tima-gui-1 | ▶ dispatched target fea_edg_spe
tima-gui-1 | 2024-01-17 06:36:04.996394 Loading spectra...
tima-gui-1 | ✖ errored target fea_edg_spe
tima-gui-1 | ✖ errored pipeline [52.935 seconds]
tima-gui-1 | Warning: Error in : Error running targets::tar_make()
tima-gui-1 | Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
tima-gui-1 | Debugging guide: https://books.ropensci.org/targets/debugging.html
tima-gui-1 | How to ask for help: https://books.ropensci.org/targets/help.html
tima-gui-1 | Last error message:
tima-gui-1 | error in evaluating the argument 'object' in selecting a method for function 'filterMsLevel': error in evaluating the argument 'object' in selecting a method for function 'Spectra': NA/NaN argument
tima-gui-1 | Last error traceback:
tima-gui-1 | create_edges_spectra(input = input_spectra, output = par_cre_edg_spe$fil...
tima-gui-1 | import_spectra(input)
tima-gui-1 | Spectra::filterMsLevel(Spectra::Spectra(MsBackendMgf::readMgf(f = file))...
tima-gui-1 | Spectra::Spectra(MsBackendMgf::readMgf(f = file))
tima-gui-1 | MsBackendMgf::readMgf(f = file)
tima-gui-1 | .extract_mgf_spectrum(mgf[begin[i]:end[i]], mapping = mapping)
tima-gui-1 | grep("=", mgf)
tima-gui-1 | is.factor(x)
tima-gui-1 | .handleSimpleError(function (cond) .Internal(C_tryCatchHelper(addr, 1L,...
tima-gui-1 | h(simpleError(msg, call))
tima-gui-1 | .handleSimple [... truncated]
tima-gui-1 | 1: shiny::runApp
tima-gui-1 exited with code 0

I can share my data in private. Thank you for your help

**Comment by Adafede** [comment]
Hi again @anani-a-missinou and thank you for opening this issue. With the first 3 lines, it looks like I can run the step without issue. Could you send me the full data? (rutz @ imsb.biol.ethz.ch)

**Comment by Adafede** [comment]
Thank you for sharing @anani-a-missinou, it looks like on line 88174 from your MGF (very end) there is an empty `BEGIN IONS` breaking things. Removing it solved the issue on my side.

**Comment by Adafede** [comment]
@anani-a-missinou Any update?

**Comment by Adafede** [comment]
I'll close for now.
