### ISSUE TITLE
Stuck to "Changing parameters... ...Advanced" since timaR 2.9.2

### ISSUE THREAD

**Issue by RemyMG** [taxonomicallyinformedannotation/tima-r#122]
Hi @Adafede,

Since version 2.9.2 timaR is stuck to parameter importation, and <http://127.0.0.1:3838> doesn't open while <http://127.0.0.1:3839> does but nothing happen. I tried on two different computers lately with same issue...

```
> shiny::runApp('C:/Users/marcellr/GitHub/tima-r/inst/app')
Loading required package: shiny
2024-02-12 14:54:15.202376 Please, go to: http://localhost:3838/ 

Listening on http://127.0.0.1:3838
2024-02-12 14:56:06.185628 Loading default params 
2024-02-12 14:56:06.328153 Changing parameters ... 
2024-02-12 14:56:06.32829 ... Small 
2024-02-12 14:56:06.330439 ... Advanced
:..
```
Last version 2.9.1 was working pretty well. 

Thanks for your help !

**Comment by RemyMG** [comment]
Hi @Adafede,

Thanks for your precious help, I tested the new version this morning and it's running smooth again! :)

**Comment by Adafede** [comment]
Glad it worked! 👍🏼
