### ISSUE TITLE
Adducts "ammonium"

### ISSUE THREAD

**Issue by AndreaCa96** [taxonomicallyinformedannotation/tima-r#127]
**Describe the bug**
I cannot start the "inst/scripts/prepare_libraries_adducts.R"

Last error message:
    objetct'ammonium' doesn't found
Last error traceback:
    prepare_libraries_adducts(str_met = lib_mer_str_met, adducts_masses_list...
    create_adducts(ms_mode = "pos")
    tidytable::mutate(tidytable::mutate(masses_table, `[1M+(H)3]3+` = (exact...
    tidytable::mutate(masses_table, `[1M+(H)3]3+` = (exact_mass +      3 * p...
    mutate.data.frame(masses_table, `[1M+(H)3]3+` = (exact_mass +      3 * p...
    mutate(.df, ..., .by = {     {         .by     } }, .keep = .keep, .befo...
    mutate.tidytable(.df, ..., .by = {     {         .by     } }, .keep = .k...
    eval_tidy(dt_expr, .df, dt_env)
    (~.df)[, `:=`(`[1M+(H)4(N)1]1+` = exact_mass + ammonium)]
    `[.data.table`(~.df, , `:=`(`[1M+(H)4(N)1]1+` = exact_mass +      ammoni...
    eval(jsub, SDenv, parent.frame())
    eval(jsub, SDenv, parent.frame())
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))

**To Reproduce**
1. Go to 'inst/scripts/prepare_libraries_adducts.R'
4. See error: Last error message:
    objetct'ammonium' doesn't found
Last error traceback:
    prepare_libraries_adducts(str_met = lib_mer_str_met, adducts_masses_list...
    create_adducts(ms_mode = "pos")
    tidytable::mutate(tidytable::mutate(masses_table, `[1M+(H)3]3+` = (exact...
    tidytable::mutate(masses_table, `[1M+(H)3]3+` = (exact_mass +      3 * p...
    mutate.data.frame(masses_table, `[1M+(H)3]3+` = (exact_mass +      3 * p...
    mutate(.df, ..., .by = {     {         .by     } }, .keep = .keep, .befo...
    mutate.tidytable(.df, ..., .by = {     {         .by     } }, .keep = .k...
    eval_tidy(dt_expr, .df, dt_env)
    (~.df)[, `:=`(`[1M+(H)4(N)1]1+` = exact_mass + ammonium)]
    `[.data.table`(~.df, , `:=`(`[1M+(H)4(N)1]1+` = exact_mass +      ammoni...
    eval(jsub, SDenv, parent.frame())
    eval(jsub, SDenv, parent.frame())
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))

**Expected behavior**
Installation of adducts library

**Screenshots**

**Desktop (please complete the following information):**

* OS: windows
* Browser chrome
* Version [e.g. 22]

**Comment by Adafede** [comment]
Hi @AndreaCa96!

I am missing some context to be able to help you.
Are you running the latest version?
If not, please remove any old version and do a clean pull/install.

Are you trying to achieve some particular intermediate library or just running the default pipeline?

Happy to help further!

**Comment by AndreaCa96** [comment]
> Hi @AndreaCa96!
> 
> I am missing some context to be able to help you. Are you running the latest version? If not, please remove any old version and do a clean pull/install.
> 
> Are you trying to achieve some particular intermediate library or just running the default pipeline?
> 
> Happy to help further!

Hi i'm download the new version but i'm have always the same problem concerning the adducts. 
Yes is the default pipeline, and the browser is edge not chrome sorry.

here it is a screenshot
![image](https://github.com/taxonomicallyinformedannotation/tima-r/assets/106172759/15851415-d98a-4d62-9b8b-5400cb21d11b)
✖ errored target lib_add
✖ errored pipeline [16.03 seconds]
Warning: Error in : Error running targets::tar_make()
Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
Debugging guide: https://books.ropensci.org/targets/debugging.html
How to ask for help: https://books.ropensci.org/targets/help.html
Last error message:
    oggetto 'ammonium' non trovato
Last error traceback:
    prepare_libraries_adducts(str_met = lib_mer_str_met, adducts_masses_list...
    create_adducts(ms_mode = "pos")
    tidytable::mutate(tidytable::mutate(masses_table, `[1M+(H)3]3+` = (exact...
    tidytable::mutate(masses_table, `[1M+(H)3]3+` = (exact_mass +      3 * p...
    mutate.data.frame(masses_table, `[1M+(H)3]3+` = (exact_mass +      3 * p...
    mutate(.df, ..., .by = {     {         .by     } }, .keep = .keep, .befo...
    mutate.tidytable(.df, ..., .by = {     {         .by     } }, .keep = .k...
    eval_tidy(dt_expr, .df, dt_env)
    (~.df)[, `:=`(`[1M+(H)4(N)1]1+` = exact_mass + ammonium)]
    `[.data.table`(~.df, , `:=`(`[1M+(H)4(N)1]1+` = exact_m [... truncated]
  5: shiny::runApp
  4: eval [inst/scripts/run_app.R#14]
  3: eval
  1: source

**Comment by Adafede** [comment]
Could you try running

```bash
Rscript inst/scripts/install.R
```

and then

```bash
Rscript inst/scripts/run_app.R
```

again and tell me if it solved the issue?

I suspect you still have some leftovers of a previous version, could this be?
Else we'll probably have to investigate further.

**Comment by AndreaCa96** [comment]
Thank you, it is something about my leftovers of a previous version!
Thank you very much for your prompt reply!

Andrea
