### ISSUE TITLE
SIRIUS use

### ISSUE THREAD

**Issue by elnurgar** [taxonomicallyinformedannotation/tima-r#132]
Dear Adriano,

Thank you for your help, I could run it finally for our data. However, I couldn't find any information on how to integrate sirius data into the tima workflow. 

Actually, I have mgf and csv file from mzmine for GNPS, tsv file for metadata and summaries folder from SIRIUS. I use GUI to export summaries.
1) Should be all cases checked when export summaries?
![image](https://github.com/taxonomicallyinformedannotation/tima-r/assets/67260554/045d68bf-bd60-4131-b7a4-f37324f1755b)
2) How to integrate this folder into the workflow? I couldn't find any place in gui to charge sirius data as zip file for exemple.

With bets regards,
Elnur

**Comment by Adafede** [comment]
Dear Elnur,

The classical workflow expects the SIRIUS workspace to be in `data/interim/annotations` and be named as `yourPattern_sirius`.
This is suboptimal for the moment, but I don't want to change the SIRIUS workflow before its version 6.0 which is imminent.
Then, I'll probably add a way to compute it directly or an additional menu in the GUI to add it if needed.

P.S.: If you want to reduce the size of the folder, you can only let the summaries in the folder, it will work without all the rest

P.P.S: I recommend exporting everything, as the goal is to rerank candidates that were not first before, else it makes very little sense.

P.P.P.S: I just updated partially the doc to make this clearer: https://taxonomicallyinformedannotation.github.io/tima-r/articles/II-preparing.html#sirius (https://github.com/taxonomicallyinformedannotation/tima-r/commit/35275ae1b22ff6f745c742f44fd5fa0b2a5ee11d)

Hope this helps

**Comment by Adafede** [comment]
@elnurgar 

I just added the possibility to load the compressed sirius workspace in case

**Comment by elnurgar** [comment]
Hi Adriano,

Thank you very much for this feature. I have tried today on our data and it works very well !
