### ISSUE TITLE
[enhancement] Completely remove empty candidates

### ISSUE THREAD

**Issue by Adafede** [taxonomicallyinformedannotation/tima-r#18]
To improve printing

**Comment by luigiquiros** [comment]
some issues i found: 

- after filtering out the candidates based on MS1 with low biological/chemical score there are 'tabs |' remaining in the output cell like: '|||||||annotation'. i guess this could be cleaned out.
- There are some time the smiles is not present, only the Inchykey.

**Comment by Adafede** [comment]
@luigiquiros Opened a different issue for the second point, thx!

**Comment by Adafede** [comment]
@luigiquiros I tried a fix with 8614b1b9259e03718e666d7f119c87b60c427302, could you try pulling everything again, rebuilding the package, and tell me if solved?

**Comment by Adafede** [comment]
Guess it is, open again if needed
