### ISSUE TITLE
Copy to clipboard button missing on documentation, vignette 3

### ISSUE THREAD

**Issue by DanielCR92** [taxonomicallyinformedannotation/tima-r#20]
On vignette 3, Performing Taxonomically Informed Metabolite Annotation, a copy to clipboard button next to the code - source(file = "inst/scripts/process_annotations.R") - is missing.

All other vignetter had this button next to the code, so I think adding it would be useful for the uniformity of the documentation.

**Comment by Adafede** [comment]
Should be fixed and live now: https://taxonomicallyinformedannotation.github.io/tima-r/articles/3-processing.html
