### ISSUE TITLE
FinalResults table not mantaining library, molecular formula and smiles information

### ISSUE THREAD

**Issue by DanielCR92** [taxonomicallyinformedannotation/tima-r#22]
I performed feature annotation using ISDB (spec_lib_matcher) and noticed that after using TIMA (annotate: FALSE for MS1 annotations on the process_annotations.yaml), in some annotated features the information in the library, molecular formula and smiles column is lost, even though the annotation coming from ISDB and containing that information is used.

I followed back to the pretreated, filled, and treated annotation files and they contained their respective information, so i think this information is lost in the last step of the process, after running source(file = "inst/scripts/process_annotations.R").

I attach the original ISDB file and the TIMA final results file.
[ISDB_annotations.zip](https://github.com/taxonomicallyinformedannotation/tima-r/files/7899634/ISDB_annotations.zip)
[FinalResults.zip](https://github.com/taxonomicallyinformedannotation/tima-r/files/7899635/FinalResults.zip)

**Comment by Adafede** [comment]
Hi @DanielCR92, thank you for your issue.

It looks like an interesting bug, sadly, I am not able to reproduce your error.
Could you also attach your config files?

Thanks

**Comment by Adafede** [comment]
@DanielCR92  I tried a fix with 8614b1b9259e03718e666d7f119c87b60c427302, could you try pulling everything again, rebuilding the package, and tell me if solved?

**Comment by DanielCR92** [comment]
Hello @Adafede! I attach the config files.

For this particular job I ran all the commands on the first vignette of the documentation (library preparation), the I ran source(file = "inst/scripts/prepare_isdb.R"), source(file = "inst/scripts/prepare_edges.R"), source(file = "inst/scripts/prepare_features_components.R") and source(file = "inst/scripts/prepare_features_classification.R"); and finally source(file = "inst/scripts/process_annotations.R").
[params.zip](https://github.com/taxonomicallyinformedannotation/tima-r/files/7903762/params.zip)

I also noticed the bug present on the final results table when running the initial example (Rscript inst/scripts/tima.R)

I'm gonna check the fix. Thank you very much!

**Comment by DanielCR92** [comment]
Ran everything again and it worked perfectly, all the information is now mantained.

Thanks!

**Comment by Adafede** [comment]
Thank you for pointing it out at the beginning! I'll close :)
