### ISSUE TITLE
Can't combine `library` when running process_annotations in neg mode

### ISSUE THREAD

**Issue by RemyMG** [taxonomicallyinformedannotation/tima-r#35]
The following error occurs when running the `process_annotations` script on annotation data generated by spectral_lib_matcher (ISDB) in **negative** ionization mode: 

<p align="center"><img src="https://i.imgur.com/hAbY7Od.png"/></p>

---

<details><summary>View raw code</summary>
<p>

```
Error in `dplyr::bind_rows()`:
! Can't combine `library` <character> and `library` <logical>.
Run `rlang::last_error()` to see where the error occurred.
```

</p></details>

---

**Comment by Adafede** [comment]
Hi @RemyMG!

Thank you for reporting!
How are you performing the spectral matching step in neg mode?

According to https://github.com/taxonomicallyinformedannotation/tima-r/blob/d39620ff6ad2c57c6750ae81007f2df6cfe94876/tests/testthat/test_functions.R#L121 there should be no issue but might be the case... happy to help diagnose if you attach your params + files! 😊

**Comment by Adafede** [comment]
Any news?

**Comment by Adafede** [comment]
@RemyMG Can I close the issue? 😜

**Comment by RemyMG** [comment]
@Adafede for sure :)
